controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # api/config/routes.yaml
auth:
    path: /auth
    methods: [ 'POST' ]
public_images:
    path: /assets/uploads/{filename}
    controller: App\Controller\PictureUrlController::show
    requirements:
        filename: .+

